# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-18 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191118_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_info',
            name='version',
            field=models.IntegerField(verbose_name='\u7248\u672c'),
        ),
    ]
