# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-18 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191118_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_info',
            name='logic_cpu_num',
            field=models.CharField(max_length=4, verbose_name='\u903b\u8f91CPU'),
        ),
        migrations.AlterField(
            model_name='system_info',
            name='physical_cpu_num',
            field=models.CharField(max_length=4, verbose_name='\u7269\u7406CPU'),
        ),
        migrations.AlterField(
            model_name='system_info',
            name='uuid',
            field=models.CharField(max_length=30, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='system_info',
            name='version',
            field=models.CharField(max_length=30, verbose_name='\u7248\u672c'),
        ),
    ]
