# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-18 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191118_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_info',
            name='logic_cpu_num',
            field=models.IntegerField(verbose_name='\u903b\u8f91CPU'),
        ),
        migrations.AlterField(
            model_name='system_info',
            name='physical_cpu_num',
            field=models.IntegerField(verbose_name='\u7269\u7406CPU'),
        ),
    ]
